// products-data.js
const allProducts = [
    // --- JEANS (J001 - J020) ---
    { id: "J001", name: "Acne Studios Baggy Fit Jeans 1981M Mid Blue Wash", price: 18500, image: "images/J1.jpg", link: "product-detail.html?id=J001" },
    { id: "J002", name: "Acne Studios Loose Fit Jeans 1981 Denim", price: 22900, image: "images/J2.jpg", link: "product-detail.html?id=J002" },
    { id: "J003", name: "Celine Men's Blue 90s Mid-Rise Selvedge Denim Jeans Indigo", price: 38000, image: "images/J3.jpg", link: "product-detail.html?id=J003" },
    { id: "J004", name: "Loewe Anagram Barrel Jeans 'Washed Denim'", price: 34500, image: "images/J4.jpg", link: "product-detail.html?id=J004" },
    { id: "J005", name: "Loewe Chain Jeans 'Washed Denim'", price: 36000, image: "images/J5.jpg", link: "product-detail.html?id=J005" },
    { id: "J006", name: "Celine Dylan Flared Jeans Signature Union Wash", price: 35500, image: "images/J6.jpg", link: "product-detail.html?id=J006" },
    { id: "J007", name: "Saint Laurent D02 M/SK-LW Distressed Skinny Fit Blue", price: 24900, image: "images/J7.jpg", link: "product-detail.html?id=J007" },
    { id: "J008", name: "Chanel Jeans Women's Denim Blue", price: 85000, image: "images/J8.jpg", link: "product-detail.html?id=J008" },
    { id: "J009", name: "Acne Studios Relaxed Fit Jeans White Green", price: 16500, image: "images/J9.jpg", link: "product-detail.html?id=J009" },
    { id: "J010", name: "Acne Studios Relaxed Fit Jeans Mid Blue Auz", price: 15900, image: "images/J10.jpg", link: "product-detail.html?id=J010" },
    { id: "J011", name: "Acne Studios Super Baggy Fit Jeans", price: 19800, image: "images/J11.jpg", link: "product-detail.html?id=J011" },
    { id: "J012", name: "Gucci Jeans Men Denim Blue", price: 32000, image: "images/J12.jpg", link: "product-detail.html?id=J012" },
    { id: "J013", name: "Loewe Deconstructed Jeans In Denim Washed Denim", price: 38000, image: "images/J13.jpg", link: "product-detail.html?id=J013" },
    { id: "J014", name: "Loewe SS22 Jeans Women's Washed Denim Blue", price: 29000, image: "images/J14.jpg", link: "product-detail.html?id=J014" },
    { id: "J015", name: "Louis Vuitton SS23 Jeans Men's Blue", price: 45000, image: "images/J15.jpg", link: "product-detail.html?id=J015" },
    { id: "J016", name: "Celine Kitty Jeans In Pismo Wash Denim", price: 39000, image: "images/J16.jpg", link: "product-detail.html?id=J016" },
    { id: "J017", name: "Bottega Veneta Belted Wide-Leg Jeans", price: 42000, image: "images/J17.jpg", link: "product-detail.html?id=J017" },
    { id: "J018", name: "SS24 Jeans Women's Dark Blue", price: 26000, image: "images/J18.jpg", link: "product-detail.html?id=J018" },
    { id: "J019", name: "Acne Studios Cut Off Jeans White Green", price: 17000, image: "images/J19.jpg", link: "product-detail.html?id=J019" },
    { id: "J020", name: "Chanel Jeans Women's Blue", price: 88000, image: "images/J20.jpg", link: "product-detail.html?id=J020" },

    // --- STREETWEAR (P001 - P020) ---
    { id: "P001", name: "Fear of God Essentials Jersey Crewneck", price: 2675, image: "images/p1black.jpg", link: "product-detail.html?id=P001" },
    { id: "P002", name: "Stussy Body Scan Tee", price: 3600, image: "images/p2ash.jpg", link: "product-detail.html?id=P002" },
    { id: "P003", name: "Vlone Smoke Demon Angel Hoodie", price: 3350, image: "images/p3white.jpg", link: "product-detail.html?id=P003" },
    { id: "P004", name: "Nike x Stussy 8 Ball T-shirt", price: 5000, image: "images/p4white.jpg", link: "product-detail.html?id=P004" },
    { id: "P005", name: "Stussy Ist Venus Pig. Dyed Tee", price: 6400, image: "images/p5blue.jpg", link: "product-detail.html?id=P005" },
    { id: "P006", name: "Mardi Mercredi Tshirt Flowermardi", price: 1100, image: "images/p6black.jpg", link: "product-detail.html?id=P006" },
    { id: "P007", name: "Mardi Mercredi Sweatshirt Flowermardi Blossom", price: 2400, image: "images/p7black.jpg", link: "product-detail.html?id=P007" },
    { id: "P008", name: "Drew House Mascot SS Tee", price: 2700, image: "images/p8black.jpg", link: "product-detail.html?id=P008" },
    { id: "P009", name: "Marithe Francois Girbaud Ringer Tee", price: 1400, image: "images/p9pink.jpg", link: "product-detail.html?id=P009" },
    { id: "P010", name: "Stussy Look Beyond Tee Black", price: 2400, image: "images/p10black.jpg", link: "product-detail.html?id=P010" },
    { id: "P011", name: "Stussy Look Beyond Tee White", price: 2400, image: "images/p11white.jpg", link: "product-detail.html?id=P011" },
    { id: "P012", name: "Lifework New Silket SS Black", price: 1400, image: "images/p12black.jpg", link: "product-detail.html?id=P012" },
    { id: "P013", name: "Uniqlo Kaws Pink BFF Tee White", price: 3400, image: "images/p13white.jpg", link: "product-detail.html?id=P013" },
    { id: "P014", name: "Carnival Calligraphy Logo Ovs Black", price: 1400, image: "images/p14black.jpg", link: "product-detail.html?id=P014" },
    { id: "P015", name: "Denim Tears Cotton Wreath Sweatshirt", price: 2400, image: "images/p15black.jpg", link: "product-detail.html?id=P015" },
    { id: "P016", name: "Carnival x Marvel Venom OVS T-Shirt", price: 2400, image: "images/p16black.jpg", link: "product-detail.html?id=P016" },
    { id: "P017", name: "ADLV Baby Face Donuts T-Shirt Black", price: 2400, image: "images/p17black.jpg", link: "product-detail.html?id=P017" },
    { id: "P018", name: "Marithe Francois Girbaud Ringer Tee Ivory", price: 2400, image: "images/p18white.jpg", link: "product-detail.html?id=P018" },
    { id: "P019", name: "Cosmic The 1975 Tee", price: 2400, image: "images/p19white.jpg", link: "product-detail.html?id=P019" },
    { id: "P020", name: "Carnival x UMBRO Striped Jersey", price: 2400, image: "images/p20white.jpg", link: "product-detail.html?id=P020" },

    // --- LUXURY (L1 - L17) ---
    { id: "L1", name: "Miu Miu Logo Sunglasses", price: 15500, image: "images/L1.jpg", link: "product-detail.html?id=L1" },
    { id: "L2", name: "Coach Nolita 19", price: 4900, image: "images/L2.jpg", link: "product-detail.html?id=L2" },
    { id: "L3", name: "Louis Vuitton Key Pouch S", price: 11500, image: "images/L3.jpg", link: "product-detail.html?id=L3" },
    { id: "L4", name: "Coach Cow Leather Belts", price: 3200, image: "images/L4.jpg", link: "product-detail.html?id=L4" },
    { id: "L5", name: "Vivienne Westwood Choker", price: 7900, image: "images/L5.jpg", link: "product-detail.html?id=L5" },
    { id: "L6", name: "Longchamp Le Pliage Green M", price: 5400, image: "images/L6.jpg", link: "product-detail.html?id=L6" },
    { id: "L7", name: "Coach Andrea Carryall Bag", price: 8500, image: "images/L7.jpg", link: "product-detail.html?id=L7" },
    { id: "L8", name: "Balenciaga Dynasty Sunglasses", price: 14900, image: "images/L8.jpg", link: "product-detail.html?id=L8" },
    { id: "L9", name: "Celine Small Triomphe Belt", price: 18500, image: "images/L9.jpg", link: "product-detail.html?id=L9" },
    { id: "L10", name: "Saint Laurent Cassandre Belt", price: 16500, image: "images/L10.jpg", link: "product-detail.html?id=L10" },
    { id: "L11", name: "Vivienne Westwood Mini Bas Relief", price: 5200, image: "images/L11.jpg", link: "product-detail.html?id=L11" },
    { id: "L12", name: "Prada Rectangle Sunglasses", price: 12900, image: "images/L12.jpg", link: "product-detail.html?id=L12" },
    { id: "L13", name: "Vivienne Westwood Bas Relief Choker", price: 8900, image: "images/L13.jpg", link: "product-detail.html?id=L13" },
    { id: "L14", name: "Vivienne Westwood Octavie Pendant", price: 6500, image: "images/L14.jpg", link: "product-detail.html?id=L14" },
    { id: "L15", name: "Gucci Interlocking G Mini Bag", price: 38000, image: "images/L15.jpg", link: "product-detail.html?id=L15" },
    { id: "L16", name: "Gucci GG Marmont Leather Belt", price: 17900, image: "images/L16.jpg", link: "product-detail.html?id=L16" },
    { id: "L17", name: "Dior DIORSignature B1U", price: 16900, image: "images/L17.jpg", link: "product-detail.html?id=L17" }
];